name: React CI/CD AWS CDK
on:
  push:
    branches:
      - master
      - "release/**"
      - "feature/**"
    paths:
      - "cdk/static_site_stack/**"
      - "cdk/app.py"
      - "src/**"
      - ".github/workflows/main.yml"
jobs:
  build:
    env:
      TESTING: ${{ true }}
    runs-on: ubuntu-latest
    steps:
      - name: Set env to dev
        if: (contains(github.ref, 'feature') || contains(github.ref, 'master'))
        run: echo "::set-env name=ENVIRONMENT::dev"
      - name: Set env to stg
        if: contains(github.ref, 'release')
        run: echo "::set-env name=ENVIRONMENT::stg"
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.x"
      - name: Install Dependencies
        run: npm install
        if: env.TESTING != true
      - name: Run Front-End Tests
        run: npm test
        env:
          CI: true
        if: env.TESTING != true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install AWS CDK
        run: npm install -g aws-cdk
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install CDK Requirements
        run: cd cdk && pip3 install -r requirements.txt
      - name: Synthesize Cloud Formation Template
        run: cd cdk && cdk ls -c environment=$ENVIRONMENT -c domain=${{ secrets.AWS_DOMAIN_NAME }} -c certificate_arn=${{ secrets.AWS_CERT_ARN }}
