name: React CI/CD AWS CDK
on:
  push:
    branches:
      - master
      - "release/**"
      - "feature/**"
    paths:
      - "cdk/static_site_stack/**"
      - "cdk/app.py"
      - "cdk/set_env_vars.sh"
      - "src/**"
      - ".github/workflows/main.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set env to dev
        if: contains(github.ref, 'feature') || contains(github.ref, 'master') || contains(github.base_ref, 'master')
        run: echo "::set-env name=ENVIRONMENT::dev"
      - name: Set env to stg
        if: contains(github.ref, 'release') || contains(github.base_ref, 'release')
        run: echo "::set-env name=ENVIRONMENT::stg"
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14.x"
      - name: Install jq to parse outputs of cdk deploy
        run: sudo apt install jq
      - name: Install Dependencies
        run: npm install
      - name: Run Front-End Tests
        run: npm test
        env:
          CI: true
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Install AWS CDK
        run: npm install -g aws-cdk@1.56.0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install CDK Requirements
        run: cd cdk && pip3 install -r requirements.txt
      - name: Synthesize Cloud Formation Template
        env:
          DOMAIN: ${{ secrets.AWS_DOMAIN_NAME }}
          CERT_ARN: ${{ secrets.AWS_CERT_ARN }}
        run: cd cdk && cdk ls -c environment=$ENVIRONMENT -c domain="$DOMAIN" -c certificate_arn="$CERT_ARN"
      - name: Deploy Stack
        env:
          DOMAIN: ${{ secrets.AWS_DOMAIN_NAME }}
          CERT_ARN: ${{ secrets.AWS_CERT_ARN }}
        run: cd cdk && cdk deploy -c environment=$ENVIRONMENT -c domain="$DOMAIN" -c certificate_arn="$CERT_ARN" --require-approval "never" --outputs-file cdk-deploy-output.json
      - name: Set Output Variables
        run: cd cdk && bash ./set_env_vars.sh &&
      - name: Log Output Variables
        run: echo $BUCKET && echo $DIST_ID && echo $ARTIFACT_BUCKET
      - name: Build Deployment Package
        run: npm run build
      - name: Deploy To S3 Bucket
        run: aws s3 sync ./build s3://$BUCKET --delete
      - name: Invalidate CloudFront Cache (stg & prod Environments)
        if: env.ENVIRONMENT == 'stg'
        run: aws cloudfront create-invalidation --distribution-id $DIST_ID --paths "/*"
